//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Seller.
    /// </summary>
    // *** Start programmer edit section *** (Seller CustomAttributes)

    // *** End programmer edit section *** (Seller CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SellerE", new string[] {
            "Role as \'Роль\'",
            "ФИО as \'ФИО\'",
            "Shop"}, Hidden=new string[] {
            "Shop"})]
    [View("SellerL", new string[] {
            "Role as \'Роль\'",
            "ФИО as \'ФИО\'"})]
    public class Seller : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.TestProject.tRole fRole;
        
        private IIS.TestProject.Shop fShop;
        
        // *** Start programmer edit section *** (Seller CustomMembers)

        // *** End programmer edit section *** (Seller CustomMembers)

        
        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (Seller.Role CustomAttributes)

        // *** End programmer edit section *** (Seller.Role CustomAttributes)
        public virtual IIS.TestProject.tRole Role
        {
            get
            {
                // *** Start programmer edit section *** (Seller.Role Get start)

                // *** End programmer edit section *** (Seller.Role Get start)
                IIS.TestProject.tRole result = this.fRole;
                // *** Start programmer edit section *** (Seller.Role Get end)

                // *** End programmer edit section *** (Seller.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Seller.Role Set start)

                // *** End programmer edit section *** (Seller.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (Seller.Role Set end)

                // *** End programmer edit section *** (Seller.Role Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Seller.ФИО CustomAttributes)

        // *** End programmer edit section *** (Seller.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Seller.ФИО Get start)

                // *** End programmer edit section *** (Seller.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Seller.ФИО Get end)

                // *** End programmer edit section *** (Seller.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Seller.ФИО Set start)

                // *** End programmer edit section *** (Seller.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Seller.ФИО Set end)

                // *** End programmer edit section *** (Seller.ФИО Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TestProject.Shop.
        /// </summary>
        // *** Start programmer edit section *** (Seller.Shop CustomAttributes)

        // *** End programmer edit section *** (Seller.Shop CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Shop"})]
        public virtual IIS.TestProject.Shop Shop
        {
            get
            {
                // *** Start programmer edit section *** (Seller.Shop Get start)

                // *** End programmer edit section *** (Seller.Shop Get start)
                IIS.TestProject.Shop result = this.fShop;
                // *** Start programmer edit section *** (Seller.Shop Get end)

                // *** End programmer edit section *** (Seller.Shop Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Seller.Shop Set start)

                // *** End programmer edit section *** (Seller.Shop Set start)
                this.fShop = value;
                // *** Start programmer edit section *** (Seller.Shop Set end)

                // *** End programmer edit section *** (Seller.Shop Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SellerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SellerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SellerE", typeof(IIS.TestProject.Seller));
                }
            }
            
            /// <summary>
            /// "SellerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SellerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SellerL", typeof(IIS.TestProject.Seller));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Seller.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSeller CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSeller CustomAttributes)
    public class DetailArrayOfSeller : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TestProject.DetailArrayOfSeller members)

        // *** End programmer edit section *** (IIS.TestProject.DetailArrayOfSeller members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Seller by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Seller.
        /// </summary>
        public DetailArrayOfSeller(IIS.TestProject.Shop fShop) : 
                base(typeof(Seller), ((ICSSoft.STORMNET.DataObject)(fShop)))
        {
        }
        
        public IIS.TestProject.Seller this[int index]
        {
            get
            {
                return ((IIS.TestProject.Seller)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TestProject.Seller dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
