//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Shop.
    /// </summary>
    // *** Start programmer edit section *** (Shop CustomAttributes)

    // *** End programmer edit section *** (Shop CustomAttributes)
    [AutoAltered()]
    [Caption("Магазин")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ShopE", new string[] {
            "Name as \'Название\'",
            "Adress as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("ShopE", "Sellers", "SellerL", false, "", "Продавцы", true, new string[] {
            ""})]
    [View("ShopL", new string[] {
            "Name as \'Название\'",
            "Adress as \'Адрес\'"})]
    public class Shop : ICSSoft.STORMNET.DataObject
    {
        
        private string fAdress;
        
        private string fName;
        
        private IIS.TestProject.DetailArrayOfSeller fSellers;
        
        // *** Start programmer edit section *** (Shop CustomMembers)

        // *** End programmer edit section *** (Shop CustomMembers)

        
        /// <summary>
        /// Adress.
        /// </summary>
        // *** Start programmer edit section *** (Shop.Adress CustomAttributes)

        // *** End programmer edit section *** (Shop.Adress CustomAttributes)
        [StrLen(255)]
        public virtual string Adress
        {
            get
            {
                // *** Start programmer edit section *** (Shop.Adress Get start)

                // *** End programmer edit section *** (Shop.Adress Get start)
                string result = this.fAdress;
                // *** Start programmer edit section *** (Shop.Adress Get end)

                // *** End programmer edit section *** (Shop.Adress Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shop.Adress Set start)

                // *** End programmer edit section *** (Shop.Adress Set start)
                this.fAdress = value;
                // *** Start programmer edit section *** (Shop.Adress Set end)

                // *** End programmer edit section *** (Shop.Adress Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Shop.Name CustomAttributes)

        // *** End programmer edit section *** (Shop.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Shop.Name Get start)

                // *** End programmer edit section *** (Shop.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Shop.Name Get end)

                // *** End programmer edit section *** (Shop.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shop.Name Set start)

                // *** End programmer edit section *** (Shop.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Shop.Name Set end)

                // *** End programmer edit section *** (Shop.Name Set end)
            }
        }
        
        /// <summary>
        /// Shop.
        /// </summary>
        // *** Start programmer edit section *** (Shop.Sellers CustomAttributes)

        // *** End programmer edit section *** (Shop.Sellers CustomAttributes)
        public virtual IIS.TestProject.DetailArrayOfSeller Sellers
        {
            get
            {
                // *** Start programmer edit section *** (Shop.Sellers Get start)

                // *** End programmer edit section *** (Shop.Sellers Get start)
                if ((this.fSellers == null))
                {
                    this.fSellers = new IIS.TestProject.DetailArrayOfSeller(this);
                }
                IIS.TestProject.DetailArrayOfSeller result = this.fSellers;
                // *** Start programmer edit section *** (Shop.Sellers Get end)

                // *** End programmer edit section *** (Shop.Sellers Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shop.Sellers Set start)

                // *** End programmer edit section *** (Shop.Sellers Set start)
                this.fSellers = value;
                // *** Start programmer edit section *** (Shop.Sellers Set end)

                // *** End programmer edit section *** (Shop.Sellers Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ShopE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ShopE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ShopE", typeof(IIS.TestProject.Shop));
                }
            }
            
            /// <summary>
            /// "ShopL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ShopL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ShopL", typeof(IIS.TestProject.Shop));
                }
            }
        }
    }
}
