//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T role.
    /// </summary>
    // *** Start programmer edit section *** (tRole CustomAttributes)

    // *** End programmer edit section *** (tRole CustomAttributes)
    public enum tRole
    {
        
        /// <summary>
        /// Руководитель.
        /// </summary>
        // *** Start programmer edit section *** (tRole.Manager CustomAttributes)

        // *** End programmer edit section *** (tRole.Manager CustomAttributes)
        [Caption("Руководитель")]
        Manager,
        
        /// <summary>
        /// Помощник.
        /// </summary>
        // *** Start programmer edit section *** (tRole.Assistant CustomAttributes)

        // *** End programmer edit section *** (tRole.Assistant CustomAttributes)
        [Caption("Помощник")]
        Assistant,
    }
}
